services:
  mindless_meals:
    build: .
    container_name: mindless_meals
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    restart: unless-stopped
    networks:
     - atlas-proxy
     - postgres_default

networks:
  atlas-proxy:
    external: true
  postgres_default:
    external: true
